### ISSUE TITLE
[TS] ValidateCustomAttributeViewStrategyBase is not defined

### ISSUE THREAD

**Issue by david-martyn-ford** [aurelia/validation#99] opened 2015-08-14 11:40 UTC
I'm using version 0.2.7 and I'm trying to create my own view strategy but I've ran into some issues. My application is using TypeScript so I'm using the **gulp-typescript** node module to compile my TS to JS(AMD).

When I try to import the strategy base as shown below I get an error.
```javascript
import {ValidateCustomAttributeViewStrategyBase}  from 'aurelia-validation';

export class ValidationViewStrategy extends ValidateCustomAttributeViewStrategyBase {
...
}
```
```
Unhandled promise rejection Error: ValidateCustomAttributeViewStrategyBase is not defined
```

I tried doing the same code just with ES6 using the navigation-skeleton and it worked fine so I assume it's an issue with TS?

**Comment by jods4** [comment] 2015-08-14 20:06
It's because there is no `.d.ts` definition of the `aurelia-validation` module yet.

In the meantime you can either:
1. declare everything as `any`
2. write your own definition file for what you need (the api surface is not large at all)
3. Ignore the errors because it should emit correct js code

**Comment by david-martyn-ford** [comment] 2015-08-15 17:38
I'd assume it would work like you said in point 3 but that is coming from the console in Chrome which means it won't just work.

**Comment by jods4** [comment] 2015-08-15 18:03
OK, I see.
It is kinda hard with so little details but I got this to work recently so I'll make a guess.

Try to go with 2. _At least_ that:
```typescript
declare module 'aurelia-validation' {
  export class ValidateCustomAttributeViewStrategyBase { };
}
```

Because I noticed that TS emits strange code when it isn't sure if you're extending from a proper class.

**Comment by PWKad** [comment] 2015-09-10 21:28
There are already open issues for TypeScript definitions, closing as duplicate of #4

**Closed by PWKad** 2015-09-10 21:28 UTC
