### ISSUE TITLE
Add d.ts generation

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validation#86] opened 2015-07-13 18:40 UTC
Other aurelia repositories export their own d.ts file by using the babel-dts-generator plugin.

It would be great if the validation repository could do the same.

**Comment by janvanderhaegen** [comment] 2015-07-20 21:31
Going to see if I can get help on this from the team!!

**Comment by Martin-Andersen** [comment] 2015-07-25 10:32
Yes please add the d.ts file, typescript is a must.

**Comment by alexmills** [comment] 2015-08-26 04:23
Any updates on whether the next release will include the d.ts file? :)

**Comment by JeroenVinke** [comment] 2015-08-28 19:12
@janvanderhaegen are you willing to accept PR's for this?

**Comment by janvanderhaegen** [comment] 2015-08-28 20:03
Willing to accept PR's for anything helpful!

**Comment by nomack84** [comment] 2015-08-29 04:51
@janvanderhaegen Here you have it #122

**Comment by PWKad** [comment] 2015-09-10 21:32
Closing as a duplicate of many others, first was #4 

Contributions still needed on this just trying to help triage the issues by narrowing down the open ones

Duplicate of #4

**Closed by PWKad** 2015-09-10 21:32 UTC
Labels: enhancement
