### ISSUE TITLE
Requirejs not supported

### ISSUE THREAD

**Issue by obany** [aurelia/validation#225] opened 2016-03-14 15:37 UTC
Requirejs is not supported as a loader for the resources, System['import'] is hard coded to load the module.

As this library is being rewritten I have created a quick fix to add requirejs support. I assume the rewrite will make better use of the PAL for this task.

PR https://github.com/aurelia/validation/pull/224

**Comment by EisenbergEffect** [comment] 2016-03-14 16:28
@PWKad This needs to be switched to use Aurelia's Loader abstraction.

**Comment by PWKad** [comment] 2016-04-11 21:48
Duplicate of #226

**Closed by PWKad** 2016-04-11 21:48 UTC
