### ISSUE TITLE
Typescript definitions missing

### ISSUE THREAD

**Issue by derkork** [aurelia/validation#245] opened 2016-05-19 13:29 UTC
Issue #133 mentions that the plugin ships with TypeScript definitions however after installing version 0.8.1 with  `jspm install` no typescript definitions are present: 
![image](https://cloud.githubusercontent.com/assets/327257/15395037/6f58af98-1dd6-11e6-881d-c372b347c07b.png)

**Comment by EisenbergEffect** [comment] 2016-05-19 13:32
@PWKad We definitely need to fix this up not only for this library but because we can't generate d.ts files for validatejs without this being addressed first.

**Comment by EisenbergEffect** [comment] 2016-05-19 13:32
closing as a duplicate of https://github.com/aurelia/validation/issues/244

**Closed by EisenbergEffect** 2016-05-19 13:32 UTC
Labels: duplicate
