### ISSUE TITLE
typescript conflicts with latest aurelia-binding

### ISSUE THREAD

**Issue by ariovistus** [aurelia/validation#479] opened 2018-03-17 13:12 UTC
**I'm submitting a bug report**

* **Library Version:**
1.1.2

**Please tell us about your environment:**
* **Operating System:**
Linux (fedora)

* **Node Version:**
6.12.0

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
TypeScript 2.7

**Current behavior:**
typescript definition file has a conflicting symbol with aurelia-binding 1.7.0:

```
/app/node_modules/aurelia-binding/dist/aurelia-binding.d.ts(39,25): error TS2451: Cannot redeclare block-scoped variable 'getContextFor'.
```

example full build: https://travis-ci.org/Retro3223/stats/builds/354708543

**Expected/desired behavior:**
it doesn't break my build

* **What is the expected behavior?**
it doesn't break my build

* **What is the motivation / use case for changing the behavior?**
it doesn't break my build

**Comment by Alexander-Taran** [comment] 2018-03-17 13:35
Can you trace down where the other declaration is?

**Comment by ariovistus** [comment] 2018-03-17 13:50
/app/node_modules/aurelia-validation/dist/commonjs/property-info.d.ts

**Comment by Alexander-Taran** [comment] 2018-03-17 19:09
going to look into it

**Comment by Alexander-Taran** [comment] 2018-03-17 21:08
seems like duplicate of https://github.com/aurelia/binding/issues/664

**Comment by ariovistus** [comment] 2018-03-18 15:15
Looks like, but it is odd I had no issue with 1.6.0, and all I had to do was revert to 1.6.0

**Comment by Alexander-Taran** [comment] 2018-03-18 16:37
@ariovistus if you parse through thosse issues it goes way back. depends on how you get typings I guess.

**Comment by Alexander-Taran** [comment] 2018-03-18 22:32
validation library released with typings fixed
can be closed

**Closed** 2018-03-18 22:43 UTC
