### ISSUE TITLE
computedFrom doesn't appear to revalidate properties that haven't changed

### ISSUE THREAD

**Issue by charlespockert** [aurelia/validation#123] opened 2015-08-29 10:09 UTC
I have the following scenario:

```
this.orderValidation = this.validation.on(this.salesOrder)
                    .ensure("StatusCode", (config) => { config.computedFrom(["DateInstalled"]) })
                    .passes(status => {
                        if (status == 0 && this.salesOrder.DeliveryBalance > 0)
                            return "The order must be fully delivered before it can be completed";

                        if (status == 0 && !this.salesOrder.DateInstalled)
                            return "You must specify an installation date before you can complete the order";

                        return undefined;
                    }); // ... few more validation props 
```

When the `DateInstalled` property changes, the validate kicks off again for `StatusCode` however, it never gets as far as calling the validation as `StatusCode` hasn't changed and it looks like the `forceDirty` logic is a little broken

The `StatusCode` value is already dirty because I've changed it previously so the following line

https://github.com/aurelia/validation/blob/master/src/validation/validation-property.js#L67

fails.

Should this not just check if `forceDirty` is true rather than checking if the target property is not dirty?

e.g.

```
  if(shouldBeDirty || this.latestValue !== newValue || forceExecution)
```

**Comment by jods4** [comment] 2015-10-16 21:50
Duplicate of #73, the fix is in PR #150.

**Comment by PWKad** [comment] 2016-04-11 21:03
Dupe

**Closed** 2016-04-11 21:03 UTC
