### ISSUE TITLE
Error in validation after moving to Webpack 4 

### ISSUE THREAD

**Issue by elmt1** [aurelia/validation#490] opened 2018-05-26 17:25 UTC
Please see comments at end of closed [issue 350](https://github.com/aurelia/validation/issues/350)

**I'm submitting a bug report**

* **Library Version:**
    "aurelia-binding": "^2.0.0",
    "aurelia-bootstrapper": "^2.2.0",
    "aurelia-dialog": "^1.0.0-rc.2.0.0",
    "aurelia-fetch-client": "^1.3.1",
    "aurelia-plugins-cookies": "^2.6.0",
    "aurelia-validation": "^1.1.3",
    "aurelia-webpack-plugin": "^3.0.0-rc.1",
    "typescript": "^2.8.3",
    "webpack": "^4.8.3",
    "webpack-cli": "^2.1.3",
    "webpack-hot-middleware": "^2.22.2"

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.1

* **NPM Version:**
6.0.1

* **JSPM OR Webpack AND Version**
Webpack 4.8.3

* **Browser:**
all

* **Language:**
TypeScript 2.8.3

**Current behavior:**

getPropertyInfo is not seeing the expression passed from ValidateController as an instanceof AccessMember (or a couple of others). This causes the following error:

Receiving error Unhandled rejection Error: Expression 'name&validate' is not compatible with the validate binding-behavior.
    at getPropertyInfo (webpack-internal:///40:37:15)
    at ValidationController.resetBinding (webpack-internal:///13:368:107)
    at Binding.binding.updateTarget (webpack-internal:///58:60:43)
    at Binding.bind (webpack-internal:///49:5033:12)
    at View.bind (webpack-internal:///1:1479:19)
    at Controller.bind (webpack-internal:///1:3492:17)
    at Controller.automate (webpack-internal:///1:3437:10)
    at eval (webpack-internal:///1:4581:18)

Although expression, which is an instance of BindingBehavior and not an instanceof AccessMember, however, expression.expression is an AccessMember. Adding a check for the nested expression.expression seems to fix the symptoms of this error but is likely not a good way of solving this problem because it could be much deeper. 

**Expected/desired behavior:**

No exception

* **What is the expected behavior?**

getPropertyInfo evaluates the expression with no errors

* **What is the motivation / use case for changing the behavior?**

To allow migration to Webpack 4

**Comment by fkleuver** [comment] 2018-05-31 01:09
As I [explained](https://github.com/aurelia/validation/issues/350#issuecomment-392299077) this is due to the way dependencies are resolved. `aurelia-validation` needs to be updated to accept `^2.0.0` as well, so the generated package-lock doesn't create a dependency graph with duplicate references. I'll create PRs for this in a moment.
It would make things easier if you closed this issue - it has an identical root cause (and solution) to the one you're referring to. Thanks!

**Closed** 2018-05-31 03:44 UTC
