### ISSUE TITLE
Strange behavior for the validation binding behavior

### ISSUE THREAD

**Issue by qraynaud** [aurelia/validation#370] opened 2016-10-25 11:19 UTC
**I'm submitting a bug report**
- **Library Version:**
  0.13.1

**Please tell us about your environment:**
- **Operating System:**
  Linux (KUbuntu 16.10)
- **Node Version:**
  6.9.1
- **NPM Version:**
  3.10.8
- **Browser:**
  all
- **Language:**
  all

**Current behavior:**

I split on multiple pages a big form to make it more usable. The routing changes on each page to allow to ref a specific part of the form with an URL. I have a simple service returning the object to be edited by the form either from cache or an API call for the first time.

I'm using this validation rules for one of the page of my form:

``` js
ValidationRules
  .ensure('username')
    .required()
    .minLength(4)
  .ensure('firstname')
    .required()
    .minLength(4)
  .ensure('lastname')
    .required()
    .minLength(4)
  .ensure('email')
    .required()
    .email()
  .on(User)
;
```

I have the following view:

``` pug
template
  form.form-horizontal(submit.delegate="user.save()")
    .form-group.has-feedback
      label.col-sm-3.control-label(for="username") Nom d'utilisateur
      .col-sm-9
        input.form-control(type="text" id="username" placeholder="Nom d'utilisateur" value.bind="user.username & validate:controller")
    .form-group.has-feedback
      label.col-sm-3.control-label(for="firstname") Prénom
      .col-sm-9
        input.form-control(type="text" id="firstname" placeholder="Prénom" value.bind="user.firstname & validate")
    .form-group.has-feedback
      label.col-sm-3.control-label(for="lastname") Nom
      .col-sm-9
        input.form-control(type="text" id="lastname" placeholder="Nom" value.bind="user.lastname & validate")
    .form-group.has-feedback
      label.col-sm-3.control-label(for="email") Email
      .col-sm-9
        input.form-control(type="email" id="email" placeholder="Email" value.bind="user.email & validate")
```

And here is my model (simplified to only keep relevant code):

``` js
@inject(UserCache, ValidationControllerFactory)
export class Edit {
  constructor(userCache, controllerFactory) {
    this.userCache = userCache;

    this.controller = controllerFactory.createForCurrentScope();
    this.controller.validateTrigger = validateTrigger.changeOrBlur;
    this.controller.addRenderer(new BootstrapFormRenderer());
  }

  activate() {
    return this.userCache.get('me')
      .then(user => {
        this.user = user;
        this.controller.validate({object: user});
      })
    ;
  }

  deactivate() {
    this.user = null;
  }
}
```

As of now, when I change one of the field to empty it during edition, the rule triggers properly the required error message. If I change to a second page of my form, the controller goes into an error state because the user object comes from cache and has now a missing property.

But when I come back on the original form, the error is reset and the error message is not printed. I added some debug in the renderer and I can confirm reset instructions are sent for every binding behaviour.

Even if I comment out the reset code, the controller does not seem to be able to relate the error to the correct binding and thus the error message is not displayed.

Another way to see this is to add `this.controller.addError('some message', this.user, 'firstname');` after the user is set in the activate promise. It is reseted right away. With resets commented out, it is never shown below the firstname field.

**Expected/desired behavior**
- **What is the expected behavior?**

I believe there should be a way of setting an initial state in the controller to display error messages properly at form display.
- **What is the motivation / use case for changing the behavior?**

I know in normal conditions you should not have errors on a form at display time, but it happens that you want an user to correct a mistake and thus to display a form that properly points out where fixes are needed.

Also, I don't think errors added with `addError()` should be so casually trashed without an explicit `reset()` call from the validation lib user (me in this case) or `removeError()` call.

**Comment by jdanyow** [comment] 2016-10-26 01:04
Errors associated with a binding are "reset" (unrendered) when the binding "unbinds". This prevents memory leaks and is the expected behavior in most cases. This is not to say your use-case does not make sense, I think it does, but we probably shouldn't change the default behavior because it would cause unexpected issues for people, especially those who are using the `if` template controller.

What if you invoked `controller.validate()` upon activation of the child page? That should display the errors.

Note: there's a bug with passing an object to the validate method like you're doing here:  `this.controller.validate({object: user});`.  It will be fixed in the upcoming release.  This might explain some of the strange behavior you're seeing.

**Comment by qraynaud** [comment] 2016-10-26 08:35
I tried calling both (`validate()` and `validate({object: user})` at activation time without success.

In both scenarios, I see a `reset` taking place just after the view activation while I don't have any reason to think that the element should be removed from the DOM. Only inserted once thus causing a bind and not an unbind.

And though I understand your point about if that might cause memory leaks, this might also be a problem. What if I have tabs in my view switching from one part of a form to another? Then switching from an error to the other part would reset it and then it might require a lot of work from the validation lib user to get the error back on screen.

Maybe you should add a parameter to allow for automatic reset or not from the binding behaviour so we can fine tune this? I think it would be more easy for me to find out where I need to manually reset to prevent memory leaks (more often than not a simple global `reset()` in the `deactivate()` method would be more than enough) than to find every place I should call `validate` manually when I tried to put a trigger that would do things automatically for me.

**Comment by qraynaud** [comment] 2016-11-11 10:25
@jdanyow : any thoughts on this?

**Comment by jdanyow** [comment] 2016-11-12 16:05
@qraynaud it would be helpful if you could provide a gist that demonstrates the behavior you're not expecting. I will be able to provide concrete suggestions if I can see exactly what is going on in your use-case.

https://gist.run/?id=3625244afe4f188785190b23f2e7f472

**Comment by jdanyow** [comment] 2016-11-26 15:31
@qraynaud closing for now- I can re-open if you provide a sample using the gist ^^^ above.

**Closed by jdanyow** 2016-11-26 15:31 UTC
Labels: question

**Comment by B3zo0** [comment] 2017-11-23 15:27
@qraynaud I'm having the same issue. Did you find a solution to this?

**Comment by qraynaud** [comment] 2017-11-24 09:55
No. I really wanted to make a gist but could not find the time. A lot happened on my side. For now I skipped validation but I will eventually have to get back to it.

**Comment by B3zo0** [comment] 2017-11-27 13:52
@qraynaud I was able to resolve my problem with setting like this.
```html
<div class="ts-form-group ts-form-group-horizontal"
   validation-errors="errors.bind: codeExpirationInSecondsErrors; controller.bind: validation">
<label textcontent.one-time="resources.codeExpiration"></label>

<div>
  <text value-in-seconds.bind="settings.codeExpirationInSeconds & validate: validation"></text>
</div>

<div class="ts-validation ts-error"
	 if.bind="codeExpirationInSecondsErrors">
  <span repeat.for="itemError of codeExpirationInSecondsErrors">
	${itemError.error.message} </br>
  </span>
</div>
</div>
```
What I saw that the controller was not the one that I wanted so this way **validation-errors="errors.bind: codeExpirationInSecondsErrors; controller.bind: validation"** passing the controller (validation is a ValidationController) and setting it here as well **validate: validation**, made it work.
