### ISSUE TITLE
Validation errors are not displayed if input control is shown on some condition

### ISSUE THREAD

**Issue by shabalin** [aurelia/validation#94] opened 2015-08-04 17:16 UTC
It should be very easy to reproduce:
```html
<div if.bind="newUser">

	<div class="form-group">
		<label for="password">Password</label>
		<input type="password" class="form-control" 
		       id="password"
		       placeholder="Password"
		       value.bind="user.password">
	</div>

</div>
```
If I remove `if.bind` it starts working

**Comment by JeroenVinke** [comment] 2015-08-04 17:19
Yes, I have noticed the same. `show.bind` works though

**Comment by jods4** [comment] 2015-08-14 20:13
I think the crux of the problem is here:
https://github.com/aurelia/validation/blob/master/src/validation/validate-custom-attribute.js#L25

`subscribeChangedHandlers` is called when your `validate` attribute changes (i.e. normally when it's first set, I am not sure if there even is code to unsubscribe should it change).

What it does is walk the DOM at this point in time and wire everything up.

The way it is coded, if some control is inserted in the DOM after-the-fact there would be no validation feedback on its UI.

**Comment by jods4** [comment] 2015-08-18 18:20
I was thinking about what is the proper way to handle this... Walking the DOM does not feel right and as reported here, you would need to subscribe to Mutation Observers if you really wanted to stay correct with respect to UI changes.

Would it be bad to use a binding behavior to explicitly wire up validation? something like: `<input value.bind="name & validation" />`.

It doesn't feel too bad for me and it has some advantages:
- Performance: no need to iterate a (possibly complex) DOM looking for specific attributes on every tags, etc. It only does the minimum amount of work that is _really_ required.
- Works well with dynamic DOM (think `if` bindings). Added / removed things get subscribed / unsubscribed properly. Note that I don't know how well the current solution works when it comes to memory leaks when removing things from the DOM.
- It can always work, even on more complex paths / expressions that are not supported by the current "DOM search" heuristic.
- We could pass more validation UI related options there.
- It's explicit which is a little verbose (bad) but clearly communicate intent (good).

What do you think?

**Comment by sn0rcha** [comment] 2015-08-19 03:50
It would be much better u could pass an attribute to tell an input field that it needs validation, makes it much easier to switch CSS frameworks as well.

**Comment by jods4** [comment] 2015-08-19 07:59
Do you have a specific syntax in mind? AFAIK you can already do: `<input value.bind='name' validate='name' />`.

But you have to repeat the field name :(

**Comment by jods4** [comment] 2015-08-25 23:52
Have been thinking more about this but I'm not coming up with great ideas... although it's an important problem that bit me no later than yesterday (workaround: replace `if` by `show`, which was acceptable in this case).

Explicit option: I realized that a simple attribute/behaviour does not fix the issue. It can't subscribe to the enclosing validation object unless we pass it as a parameter, which is too verbose I think. Currently subscription is done in a top-down way by the main `validate` binding. So this would need some way to find an "ambient", "enclosing" binding property... not sure how/if it could be done efficiently.

Implicit option: The other approach would be to try to fix the current design. It would need to respond to DOM changes, probably using `MutationObserver`. Infrastructure for this is already in Aurelia. It's encapsulated in several abstractions: `ChildObserver` from `aurelia-templating` or `sync` attribute.

Note that this kind of "binding that affects the whole DOM subtree" is not unique to validation. I was musing over a custom attribute to disable all forms controls beneath it and it has very similar constraints (e.g. a `<input>` that appears in a dynamic `if.bind` should be affected). It would be nice if we could come up with a reusable, efficient solution to this problem.

Any idea?

**Comment by easyt** [comment] 2016-01-27 14:27
@EisenbergEffect,

We are having a similar issue. Our form fields are dynamically created via a binding to an object that describes the fields to be displayed. The form's validate attribute is bound before the DOM for the fields have been added. This has the effect of having the subscribeChangedHandlers run when there are no fields present.

Here is a snippet of our markup:

```html
<form role="form" validate.bind="validationInfo">
    <template repeat.for="item of metadataItems">
        <compose
            model.bind="{
                metadata: item,
                parameters: parameters
            }"
            view-model="${ getParameterViewModel(item) }">
        </compose>
    </template>
</form>
```

Could you think of a workaround or solution to this?

**Comment by EisenbergEffect** [comment] 2016-01-27 14:52
@PWKad Can you look at this issue?

**Comment by easyt** [comment] 2016-01-27 15:01
Thanks in advance for your help @PWKad @EisenbergEffect

**Comment by PWKad** [comment] 2016-05-05 17:52
Thanks for submitting this / commenting on this.  At this time we are closing this because we have completely re-written and are deprecating the previous feature set.  If you feel this should be re-opened please feel free to review [this blog post](http://blog.durandal.io/2016/05/03/aurelias-new-validation-and-testing-capabilities/) and submit either again on this repository, or on the new [validatejs bridge repository](https://github.com/aurelia/validatejs)

Thanks again!

**Closed by PWKad** 2016-05-05 17:52 UTC
